/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.postgresql.core.BaseConnection;


/**
 *
 * @author asael
 */
public class Menu extends javax.swing.JFrame {
     private InfoCurrentUser infoUsuarioActual;//guardar la informacion del usuario actual
    /**
     * Creates new form Menu
     */
    public Menu(InfoCurrentUser infoUsuarioActual) {
        this.infoUsuarioActual = infoUsuarioActual;//usuario actual
        //System.out.println("user actual: "+infoUsuarioActual.getCorreo()+","+infoUsuarioActual.getIdPersona());

        initComponents();
        this.setLocationRelativeTo(null);
    }

    public Menu() {
    }


    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        usuariosButton = new javax.swing.JButton();
        insectosButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        generarReporteButton = new javax.swing.JButton();
        generarImagenes = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pngtree-store-is-lit-at-night-image_2518772.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usuariosButton.setBackground(new java.awt.Color(179, 185, 192));
        usuariosButton.setForeground(new java.awt.Color(0, 0, 0));
        usuariosButton.setText("Editar Usuarios");
        usuariosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariosButtonActionPerformed(evt);
            }
        });
        getContentPane().add(usuariosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 120, -1));

        insectosButton.setBackground(new java.awt.Color(179, 185, 192));
        insectosButton.setForeground(new java.awt.Color(0, 0, 0));
        insectosButton.setText("Editar Insectos");
        insectosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insectosButtonActionPerformed(evt);
            }
        });
        getContentPane().add(insectosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 120, -1));

        exitButton.setBackground(new java.awt.Color(153, 0, 0));
        exitButton.setForeground(new java.awt.Color(255, 255, 255));
        exitButton.setText("Salir");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 70, -1));

        generarReporteButton.setBackground(new java.awt.Color(0, 0, 255));
        generarReporteButton.setForeground(new java.awt.Color(255, 255, 255));
        generarReporteButton.setText("Generar Reporte");
        generarReporteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarReporteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(generarReporteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, -1, -1));

        generarImagenes.setBackground(new java.awt.Color(179, 185, 192));
        generarImagenes.setForeground(new java.awt.Color(0, 0, 0));
        generarImagenes.setText("Ver Imágenes");
        generarImagenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarImagenesActionPerformed(evt);
            }
        });
        getContentPane().add(generarImagenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 120, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Menu");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/6b94a1cc87f3c2e269190155797bdb0a.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 680, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void usuariosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariosButtonActionPerformed
        // TODO add your handling code here:
        ModificacionUsuarios frameActual = new ModificacionUsuarios(infoUsuarioActual);
        frameActual.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_usuariosButtonActionPerformed

    private void insectosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insectosButtonActionPerformed
        // TODO add your handling code here:
        ModificarInsectos newFrame = new ModificarInsectos(infoUsuarioActual);
        newFrame.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_insectosButtonActionPerformed

    private void generarImagenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarImagenesActionPerformed
        // TODO add your handling code here:
        VisualizarImagenesEspecimen verjpg = new VisualizarImagenesEspecimen();
        verjpg.verImagenes();
    }//GEN-LAST:event_generarImagenesActionPerformed

    private void generarReporteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarReporteButtonActionPerformed
         try {
             // TODO add your handling code here:
             Reporte.generarPDF(); // Llama al método para generar el PDF
         } catch (SQLException ex) {
             Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_generarReporteButtonActionPerformed

    
                                     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitButton;
    private javax.swing.JButton generarImagenes;
    private javax.swing.JButton generarReporteButton;
    private javax.swing.JButton insectosButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton usuariosButton;
    // End of variables declaration//GEN-END:variables
}
